### ISSUE TITLE
preprocessing of sleepedf causes an error.

### ISSUE THREAD

**Issue by iPsych** [weiming1122/paper-automatic-sleep-staging#1]
The downloading works properly, but the sleepedf preprocessing causes below error. 
Did you conducted any additional data cleaning/align before run preprocess?

[INFO ] Loading ...
[INFO ] Signal file: data/sleepedf/sleep-cassette/SC4001E0-PSG.edf
[INFO ] Annotation file: data/sleepedf/sleep-cassette/SC4001EC-Hypnogram.edf
[INFO ] Start datetime: 1989-04-24 16:13:00
[INFO ] File duration: 79500 sec
[INFO ] Epoch duration: 30.0 sec
[INFO ] Select channel: EEG Fpz-Cz
[INFO ] Select channel samples: 7950000
[INFO ] Sample rate: 3.3333333333333335
Traceback (most recent call last):
  File "preprocess_sleepedf.py", line 195, in <module>
    main()
  File "preprocess_sleepedf.py", line 107, in main
    assert len(signals) == n_epochs, f"signal: {signals.shape} != {n_epochs}"
AssertionError: signal: (79500, 100) != 2650

**Comment by weiming1122** [comment]
It seems that you got wrong sampling rate.

**Comment by iPsych** [comment]
@weiming1122 you mean I downloaded wrong file or have some wrong setting in the preprocess_sleepedf.py?

**Comment by weiming1122** [comment]
I guess it might caused by version of pyedflib, because sampling rate is directly read by pyedflib. My pyedflib version is '0.1.29'.
![result](https://github.com/weiming1122/1D-ResNet-SE-LSTM/assets/127822437/e9addb31-460a-45fc-965a-3eef930d2271)

**Comment by iPsych** [comment]
Thanks. That was it! The newest version of pyedflib was the source of the problem.
